name: Static pages deployment to S3 Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true # fix
      APP_ENV: production
      APP_NETWORK_ID: ${{ secrets.APP_NETWORK_ID }}
      APP_CHAIN_ID: ${{ secrets.APP_CHAIN_ID }}
      APP_BUGSNAG_KEY: ${{ secrets.APP_BUGSNAG_KEY }}
      APP_BASE_URL: ${{ secrets.APP_BASE_URL }}
      APP_NETWORK: ${{ secrets.APP_NETWORK }}
      APP_DEFAULT_ORDER_EXPIRY_SECONDS: ${{ secrets.APP_DEFAULT_ORDER_EXPIRY_SECONDS }}
      APP_AIRDROP_API: ${{ secrets.APP_AIRDROP_API }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
      SOURCE_DIR: dist
      DEST_DIR: www
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc

      - name: Install Dependencies
        run: yarn install

      - name: Building the project
        run: yarn build

      - name: Generating the static pages
        run: yarn generate

      - name: Use AWS CLI
        uses: chrislennon/action-aws-cli@v1.1

      - name: Sync to S3 bucket
        run: aws s3 sync dist/ s3://$AWS_S3_BUCKET/www --follow-symlinks --delete --exclude 'static/chart/*'

      - name: Set Cache Headers
        run: aws s3 cp s3://$AWS_S3_BUCKET/www s3://$AWS_S3_BUCKET/www --exclude '*.jpg' --exclude '*.png' --exclude '*.html' --cache-control max-age=31536000,public --expires 2034-01-01T00:00:00Z --recursive

      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
