name: DEX deployment to the staging env

on:
  push:
    branches:
      - staging

jobs:
  deploy:
    env:
      ## Public
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
      APP_BASE_URL: https://staging.injective.exchange
      APP_MAINTENANCE_ENABLED: false
      APP_NETWORK: staking
      APP_ENV: staging
      SOURCE_DIR: dist
      DEST_DIR: www

      ## Secret
      APP_FEE_RECIPIENT: ${{ secrets.APP_FEE_RECIPIENT }}
      APP_BUGSNAG_KEY: ${{ secrets.APP_BUGSNAG_KEY }}
      APP_ALCHEMY_KEY: ${{ secrets.APP_ALCHEMY_KEY }}
      APP_ALCHEMY_KOVAN_KEY: ${{ secrets.APP_ALCHEMY_KOVAN_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_STAGING_BUCKET }}
      CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_STAGING_DISTRIBUTION_ID }}
      AWS_REGION: ${{ secrets.AWS_STAGING_REGION }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{secrets.NPM_AUTH_TOKEN}}" > .npmrc

      - name: Install Dependencies
        run: yarn install

      - name: Building the project
        run: yarn build

      - name: Generating the static pages
        run: yarn generate

      - name: Use AWS CLI
        uses: chrislennon/action-aws-cli@v1.1

      - name: Sync to S3 bucket
        run: aws s3 sync dist/ s3://$AWS_S3_BUCKET/www --follow-symlinks --delete --exclude 'static/chart/*'

      - name: Set Cache Headers
        run: aws s3 cp s3://$AWS_S3_BUCKET/www s3://$AWS_S3_BUCKET/www --exclude "*" --include "*.js" --include "*.css" --include "*.svg" --include "*.woff2" --include "*.woff" --include "*.ttf" --recursive --metadata-directive REPLACE --expires 2034-01-01T00:00:00Z --cache-control max-age=2592000,public

      - name: Invalidate Cloudfront CDN
        run: aws cloudfront create-invalidation --distribution-id=$CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
